server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url:  jdbc:mysql://ruodb.c9nfniti19nu.ap-northeast-2.rds.amazonaws.com:3306/ruo # 변경해주세요
    username:admin
    password:qwe594700
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
